name: JobSimulator.dev Test Checker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/puppeteer/puppeteer:19.7.2
      # image: lironavon/docker-puppeteer-container:16.10.0
      options: --cap-add=SYS_ADMIN --user 1001
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      - name: npm install
        run: npm i && cd .github/workflows && npm i && cd ../..

      # - name: Run Tests
      #   timeout-minutes: 1
      #   run: node .github/workflows/test.js
      - name: build app
        run: npx webpack

      - name: start webpack server
        run: npx webpack serve &

      - name: start backend
        run: npm run start-json-server &

      - name: Run Tests
        # run: (timeout 30s (npx .github/workflows/node_modules/uvu .github/workflows >> results.txt)) || [[ $? -eq 124 ]] && echo "Done Testing."
        # run: (timeout 60s node .github/workflows/test.js >> results.txt) || echo "Done Testing."
        # run: timeout 15s node .github/workflows/test.js > results.txt || echo 'Done Testing. Results below:' && cat results.txt
        run: node .github/workflows/test.js # > results.txt || echo 'Done Testing. Results below:' && cat results.txt


      # - name: Archive code coverage results
      #   uses: actions/upload-artifact@v3
      #   with:
      #     path: results.txt
      #     retention-days: 5

      # - name: Check if Tests Passed
      #   run: "grep -q 'Passed:    4' results.txt"
